server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: chuchen-ai-code-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chuchen_ai_code
    username: root
    password: 12345678

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chuchen.chuchenaicodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
